# Generated by Django 6.1 on 2026-09-08 09:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('title', models.CharField(max_length=350, verbose_name='عنوان سیاست')),
                ('description', models.TextField(verbose_name='توضیحات تکمیلی')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعالیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ و زمان آخرین بروزرسانی')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('name', models.CharField(max_length=200, verbose_name='نام طبقه بندی')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('name', models.CharField(max_length=60, verbose_name='نام کشور')),
                ('code', models.CharField(max_length=6, verbose_name='کد کشور')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('name', models.CharField(max_length=20, verbose_name='نام شهرستان')),
                ('code', models.CharField(max_length=6, verbose_name='کد شهرستان')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('property_type', models.CharField(choices=[('villa', 'ویلا'), ('cottage', 'کلبه'), ('apartment', 'آپارتمان'), ('suite', 'سوئیت'), ('house', 'خانه'), ('eco_lodge', 'بوم\u200cگردی')], max_length=20, verbose_name='نوع ملک')),
                ('max_guests', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد مهمان')),
                ('bedrooms', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد اتاق ')),
                ('beds', models.PositiveIntegerField(verbose_name='تعداد تخت')),
                ('bathrooms', models.PositiveIntegerField(default=1, verbose_name='تعداد حمام')),
                ('toilets', models.PositiveIntegerField(default=1, verbose_name='تعداد سرویس بهداشتی ')),
                ('building_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مساحت ساختمان')),
                ('land_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مساحت زمین')),
                ('floor', models.IntegerField(default=1, verbose_name='طبقه')),
                ('status', models.CharField(choices=[('draft', 'پیش نویس'), ('pending_review', 'در انتظار برسی'), ('published', 'منتشر شده'), ('rejected', 'رد شده'), ('paused', 'متوقف شده'), ('suspended', 'تعلیق شده'), ('archived', 'بایگانی شده')], default='draft', max_length=30, verbose_name='وضعیت اقامتگاه')),
                ('verification_status', models.CharField(choices=[('unverified', 'تاییدنشده'), ('pending', 'در انتظار بررسی'), ('verified', 'تاییدشده'), ('rejected', 'ردشده')], max_length=20, verbose_name='وضعیت تایید بازرس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CancellationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_before_checkin', models.PositiveIntegerField(verbose_name='تعداد ساعت های باقی مانده')),
                ('hours_before_checkin_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر ساعت باقی مانده ')),
                ('refund_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='درصد بازگشت وجه')),
                ('charge_first_night', models.BooleanField(default=False, verbose_name='کسر هزینه شب اول')),
                ('note', models.CharField(max_length=1000, verbose_name='توضیحات کوتاه برای نمایش در فاکتور')),
                ('priority', models.PositiveIntegerField(verbose_name='ترتیب برسی قانون')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='properties.cancellationpolicy', verbose_name='سیاست لغو')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('name', models.CharField(max_length=35, verbose_name='نام بخش')),
                ('code', models.CharField(max_length=6, verbose_name='کد بخش')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rural_districts', to='properties.county', verbose_name='شهرستان')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('name', models.CharField(max_length=50, verbose_name='نام شهر')),
                ('code', models.CharField(max_length=6, verbose_name='کد شهر')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='properties.county', verbose_name='شهرستان')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='properties.district', verbose_name='بخش')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cancellationpolicy',
            name='property_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_policies', to='properties.property', verbose_name='اقامتگاه'),
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('name', models.CharField(max_length=50, verbose_name='نام امکانات رفاهی')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='properties.category', verbose_name='طبقه بندی ')),
                ('property_obj', models.ManyToManyField(related_name='amenities', to='properties.property', verbose_name='اقامتگاه\u200cها')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/images/', verbose_name='تصویر')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='متن جایگزین')),
                ('is_cover', models.BooleanField(default=False, verbose_name='تصویر اصلی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی')),
                ('property_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='اقامتگاه')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=350, null=True, verbose_name='آدرس تکمیلی')),
                ('postal_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='طول جغرافیایی')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='properties.city', verbose_name='شهر')),
                ('property_obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='properties.property', verbose_name='موقعیت مکانی')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_key', models.CharField(choices=[('party', 'مهمانی'), ('smoking', 'سیگار'), ('pets', 'حیوانات خانگی'), ('quiet_hours', 'ساعات سکوت'), ('check_in', 'ورود'), ('check_out', 'خروج'), ('extra_guests', 'مهمان اضافه'), ('visitors', 'مراجعه\u200cکننده'), ('age_restriction', 'محدودیت سنی'), ('filming', 'فیلم\u200cبرداری و عکاسی'), ('event', 'برگزاری مراسم')], max_length=50, verbose_name='نوع قانون')),
                ('amenity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='properties.amenity', verbose_name='امکانات')),
                ('property_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='properties.property', verbose_name='ملک')),
            ],
        ),
        migrations.CreateModel(
            name='PermissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=False, verbose_name='مجوز')),
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permission', to='properties.propertyrule', verbose_name='قانون')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unverified', 'تاییدنشده'), ('pending', 'در انتظار بررسی'), ('verified', 'تاییدشده'), ('rejected', 'ردشده')], max_length=20, verbose_name='وضعیت تایید')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و زمان تأیید')),
                ('rejection_reason', models.TextField(blank=True, max_length=1000, null=True, verbose_name='دلیل رد ')),
                ('admin_note', models.TextField(blank=True, max_length=1000, null=True, verbose_name='یادداشت مدیر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ و زمان آخرین بروزرسانی')),
                ('property_obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='properties.property', verbose_name='اقامتگاه')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('name', models.CharField(max_length=25, verbose_name='نام استان')),
                ('code', models.CharField(max_length=6, verbose_name='کد استان')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='properties.country', verbose_name='کشور')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='county',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counties', to='properties.province', verbose_name='استان'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='properties.province', verbose_name='استان'),
        ),
        migrations.CreateModel(
            name='QuantityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد مجاز')),
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quantity', to='properties.propertyrule', verbose_name='قانون')),
            ],
        ),
        migrations.CreateModel(
            name='RuralDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('name', models.CharField(max_length=50, verbose_name='نام دهستان')),
                ('code', models.CharField(max_length=6, verbose_name='کد دهستان')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruraldistricts', to='properties.district', verbose_name='بخش')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('rule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time', to='properties.propertyrule', verbose_name='قانون')),
            ],
        ),
    ]
