# Generated by Django 6.1 on 2026-09-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_amenity_slug_alter_cancellationpolicy_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'ملک', 'verbose_name_plural': 'املاک'},
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='property_obj',
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='properties', to='properties.amenity', verbose_name='امکانات رفاهی'),
        ),
    ]
