# Generated by Django 6.1 on 2026-09-17 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_options_remove_amenity_property_obj_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'شهر', 'verbose_name_plural': 'شهر ها'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'کشور', 'verbose_name_plural': 'کشور ها'},
        ),
        migrations.AlterModelOptions(
            name='county',
            options={'verbose_name': 'شهرستان/ناحیه', 'verbose_name_plural': 'شهرستان ها/ناحیه ها'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'بخش', 'verbose_name_plural': 'بخش ها'},
        ),
        migrations.AlterModelOptions(
            name='province',
            options={'verbose_name': 'استان/ایالت ', 'verbose_name_plural': 'استان ها / ایالت ها'},
        ),
        migrations.AlterModelOptions(
            name='ruraldistrict',
            options={'verbose_name': 'دهستان/روستا', 'verbose_name_plural': 'دهستان ها/روستا ها'},
        ),
    ]
