# Generated by Django 6.1 on 2026-09-18 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_city_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name': 'امکانات رفاهی', 'verbose_name_plural': 'مدیریت امکانات رفاهی'},
        ),
        migrations.AlterModelOptions(
            name='cancellationpolicy',
            options={'verbose_name': 'سیاست لغو', 'verbose_name_plural': 'قوانین لغو رزرو'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'مدیریت دسته بندی ها'},
        ),
    ]
