# Generated by Django 6.1 on 2026-09-19 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_amenity_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyverification',
            options={'ordering': ('-created_at',), 'verbose_name': 'وضعیت تایید ملک', 'verbose_name_plural': 'وضعیت های تایید ملک'},
        ),
    ]
