# Generated by Django 6.1 on 2026-09-27 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_propertyverification_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='properties.county', verbose_name='شهرستان'),
        ),
        migrations.AlterField(
            model_name='property',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'تاییدنشده'), ('pending', 'در انتظار بررسی'), ('verified', 'تاییدشده'), ('rejected', 'ردشده')], default='unverified', max_length=20, verbose_name='وضعیت تایید بازرس'),
        ),
        migrations.AlterField(
            model_name='ruraldistrict',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rural_districts', to='properties.district', verbose_name='بخش'),
        ),
    ]
